"""Blocking measurement -> reports/blocking_report.md.

Usage (from code/business_entity_resolution/, after blocking generate/tune/prune):
    python -m src.blocking_report
"""

from __future__ import annotations

import json
import random

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

from .blocking import (BUDGET_PATH, GRID_BIGK, GRID_K, KEY_TYPES, MAX_BLOCK, country_list, iter_pairs,
                       oracle, pair_codes, stats_path, true_mask)
from .data import CACHE, REPORTS, SEED, gt_pairs, log
from .eda import md_table, p2, pct

NEAR_NAME, NEAR_ADDR = 90, 85


def cand_stats(counts: np.ndarray) -> list[str]:
    """mean / p50 / p95 / max of candidates per S1 (zeros included)."""
    return [f"{counts.mean():.1f}", f"{np.percentile(counts, 50):.0f}", f"{np.percentile(counts, 95):.0f}",
            f"{counts.max():,}"]


def main() -> None:
    rng = random.Random(SEED)
    budget = json.loads(BUDGET_PATH.read_text(encoding="utf-8"))
    k0, K0 = budget["k"], budget["K"]
    gt = gt_pairs()
    gt_codes = np.sort(pair_codes(gt["s1"].to_numpy(), gt["src"].to_numpy(), gt["idx"].to_numpy()))
    rec1 = pq.read_table(CACHE / "train_records.parquet", columns=["idx", "country"], filters=[("src", "=", 1)]).to_pandas()
    n_s1_total = int(rec1["idx"].max()) + 1
    t_all = np.bincount(gt["s1"].to_numpy(), minlength=n_s1_total)
    lines = ["# Blocking report (v1)", "",
             f"Generated by `python -m src.blocking_report`. Blocks with n_S1 x n_S2S3 > {MAX_BLOCK:,} are skipped. "
             f"Chosen budget: **k={k0}** (record's top-k S1) **OR K={K0}** (S1's top-K records), the smallest pair "
             f"budget within 0.002 of the best train oracle macro F0.5 ({budget['best_oracle_f05']:.5f}).", ""]

    # ------------------------------------------------------------- per key type
    kt_rows, pre_rows, grid_rows, runtime_rows = [], [], [], []
    missed_frames = []
    train_cps: dict[str, np.ndarray] = {}
    density = {}
    for country in country_list("train"):
        st = json.loads(stats_path("train", country).read_text(encoding="utf-8"))
        runtime_rows.append(["train", country, f"{st['timing']['keys'] / 60:.1f}", f"{st['timing']['pairs'] / 60:.1f}",
                             f"{st['timing']['total'] / 60:.1f}", f"{st['peak_rss_gib']:.1f}"])
        log(f"report: {country}")
        g = gt[gt["country"] == country]
        n_true = len(g)
        s1_ids = rec1.loc[rec1["country"] == country, "idx"].to_numpy()
        t = t_all[s1_ids]
        n_rec = pq.read_table(CACHE / "train_records.parquet", columns=["src"],
                              filters=[("country", "=", country)]).num_rows - len(s1_ids)
        cfgs = [(k, K) for k in GRID_K for K in GRID_BIGK]
        acc = {c: {"pairs": 0, "tp": np.zeros(n_s1_total, np.int64), "cps": np.zeros(n_s1_total, np.int64),
                   "t2": 0, "t3": 0} for c in cfgs}
        kt_found = np.zeros(len(KEY_TYPES), np.int64)
        kt_only = np.zeros(len(KEY_TYPES), np.int64)
        n_pairs = n_found = 0
        kept_true_codes, near_n, near_tp = [], 0, 0
        best = {2: np.full(n_s1_total * 4, -1.0, np.float32), 3: np.full(n_s1_total * 4, -1.0, np.float32)}
        for df in iter_pairs("train", country, ["s1", "src", "idx", "bits", "sim_name", "sim_addr", "score",
                                                "rank_r", "rank_s"]):
            s1, src, idx = df["s1"].to_numpy(), df["src"].to_numpy(), df["idx"].to_numpy()
            is_true = true_mask(gt_codes, s1, src, idx)
            bits = df["bits"].to_numpy().astype(np.int64)
            n_pairs += len(df)
            n_found += int(is_true.sum())
            for i in range(len(KEY_TYPES)):
                kt_found[i] += int(((bits & (1 << i)) > 0)[is_true].sum())
                kt_only[i] += int((bits[is_true] == (1 << i)).sum())
            rr, rs = df["rank_r"].to_numpy(), df["rank_s"].to_numpy()
            for (k, K) in cfgs:
                keep = (rr <= k) | (rs <= K)
                a_ = acc[(k, K)]
                a_["pairs"] += int(keep.sum())
                kt_ = keep & is_true
                a_["tp"] += np.bincount(s1[kt_], minlength=n_s1_total)
                a_["cps"] += np.bincount(s1[keep], minlength=n_s1_total)
                a_["t2"] += int(kt_[src == 2].sum())
                a_["t3"] += int(kt_[src == 3].sum())
                if (k, K) == (k0, K0):
                    kept_true_codes.append(pair_codes(s1[kt_], src[kt_], idx[kt_]))
                    near = keep & (df["sim_name"].to_numpy() >= NEAR_NAME) & (df["sim_addr"].to_numpy() >= NEAR_ADDR)
                    near_n += int(near.sum())
                    near_tp += int((near & is_true).sum())
                    sc = df["score"].to_numpy()
                    for s_ in (2, 3):
                        m = keep & (src == s_)
                        if len(best[s_]) <= idx[m].max(initial=0):
                            best[s_] = np.concatenate([best[s_], np.full(int(idx[m].max()) + 1, -1.0, np.float32)])
                        np.maximum.at(best[s_], idx[m], sc[m])
            del df
        for i, name in enumerate(KEY_TYPES):
            ks = st["key_types"].get(name, {"blocks": 0, "skipped": 0, "raw_pairs": 0})
            kt_rows.append([country, name, f"{ks['blocks']:,}", f"{ks['skipped']:,}", f"{ks['raw_pairs']:,}",
                            pct(kt_found[i], n_true), f"{int(kt_only[i]):,}"])
        pre_rows.append([country, f"{st['n_keys']:,}", f"{st['raw_pairs_total']:,}", f"{n_pairs:,}",
                         pct(n_found, n_true), f"{st['true_pairs_sharing_any_key']:,}",
                         f"{st['true_pairs_lost_to_skipped_blocks']:,}"])
        for (k, K) in cfgs:
            a_ = acc[(k, K)]
            tp, cps = a_["tp"][s1_ids], a_["cps"][s1_ids]
            res = oracle(tp, t, s1_ids)
            grid_rows.append([country, k, K, f"{a_['pairs']:,}", *cand_stats(cps),
                              p2(tp.sum(), n_true), p2(a_["t2"], (g["src"] == 2).sum()), p2(a_["t3"], (g["src"] == 3).sum()),
                              p2(((tp == t) & (t > 0)).sum(), (t > 0).sum()), f"{res['overall']:.5f}",
                              f"{res['by_type'].get('singleton', {}).get('score', float('nan')):.4f}",
                              f"{res['by_type'].get('non_singleton', {}).get('score', float('nan')):.4f}",
                              f"{1 - a_['pairs'] / (len(s1_ids) * n_rec):.6f}",
                              "**chosen**" if (k, K) == (k0, K0) else ""])
        train_cps[country] = acc[(k0, K0)]["cps"][s1_ids]
        kc = np.sort(np.concatenate(kept_true_codes)) if kept_true_codes else np.array([], np.int64)
        gcode = pair_codes(g["s1"].to_numpy(), g["src"].to_numpy(), g["idx"].to_numpy())
        pp = np.searchsorted(kc, gcode)
        found = (kc[np.minimum(pp, len(kc) - 1)] == gcode) if len(kc) else np.zeros(len(g), bool)
        missed_frames.append(g[~found])
        bb = np.concatenate([best[2][best[2] >= 0], best[3][best[3] >= 0]])
        density[("train", country)] = {"near_per_s1": near_n / len(s1_ids), "near_precision": near_tp / max(near_n, 1),
                                       "near_recall": near_tp / n_true, "best_q": np.percentile(bb, [5, 25, 50, 75, 95]),
                                       "rec_with_cand": len(bb) / n_rec}
        del acc, best

    lines += ["## 1. Key types (train)", "",
              "Block type = key type on the S2/S3 side. Raw pairs = sum of n_S1 x n_S2S3 over kept blocks. "
              "'Found' = true pairs among the distinct (unpruned) pairs carrying that key type.", "",
              md_table(["country", "key type", "blocks", "skipped blocks", "raw pairs", "true pairs found",
                        "found ONLY by this type"], kt_rows), "",
              "## 2. Before pruning (train)", "",
              md_table(["country", "keys", "raw pairs", "distinct pairs", "pair recall",
                        "true pairs sharing >= 1 key", "true pairs lost to skipped blocks only"], pre_rows), "",
              "## 3. Pruning grid (train)", "",
              "Candidates per S1 include S1s with zero candidates. Oracle = predict GT ∩ candidates, scored "
              "with `metrics.macro_f05`. Reduction ratio = 1 - pairs / (n_S1 x n_S2S3) within the country.", "",
              md_table(["country", "k", "K", "pairs", "cand/S1 mean", "p50", "p95", "max", "pair recall",
                        "recall S2", "recall S3", "S1 with ALL matches", "oracle F0.5", "singleton",
                        "non-singleton", "reduction ratio", ""], grid_rows), "",
              "Overall (all train countries):", "",
              md_table(["k", "K", "pairs", "oracle F0.5", *[f"oracle {c}" for c in budget["grid"][0]["by_country"]]],
                       [[gr["k"], gr["K"], f"{gr['pairs']:,}", f"{gr['oracle_f05']:.5f}",
                         *[f"{v:.5f}" for v in gr["by_country"].values()]] for gr in budget["grid"]]), ""]

    # ------------------------------------------------------------- missed pairs
    missed = pd.concat(missed_frames, ignore_index=True)
    flag_cols = ["addr_empty", "name_has_indic", "name_is_web", "name_has_marker", "addr_has_landmark", "addr_has_pobox"]
    ftbl = pq.read_table(CACHE / "train_records.parquet", columns=["src"] + flag_cols)
    srcs = ftbl.column("src").to_numpy()
    offs = {s_: int(np.flatnonzero(srcs == s_)[0]) for s_ in (1, 2, 3)}

    def rpos(src_: np.ndarray, idx_: np.ndarray) -> np.ndarray:
        """Row position in train_records.parquet of records (src, idx)."""
        return np.select([src_ == 1, src_ == 2], [offs[1], offs[2]], offs[3]) + idx_

    m_rec = rpos(missed["src"].to_numpy(), missed["idx"].to_numpy())
    m_s1 = rpos(np.ones(len(missed), int), missed["s1"].to_numpy())
    all_rec = rpos(gt["src"].to_numpy(), gt["idx"].to_numpy())
    labels = {"addr_empty": "record address empty", "name_has_indic": "record name Indic",
              "name_is_web": "record name web", "name_has_marker": "record name marker",
              "addr_has_landmark": "record address landmark", "addr_has_pobox": "record address PO box"}
    flag_rows = []
    for col, lab in labels.items():
        v = ftbl.column(col).to_numpy(zero_copy_only=False)
        flag_rows.append([lab, pct(v[m_rec].sum(), len(missed)), f"{v[all_rec].mean() * 100:.2f}%"])
    v = ftbl.column("addr_empty").to_numpy(zero_copy_only=False)
    flag_rows.append(["S1 address empty", pct(v[m_s1].sum(), len(missed)), f"{v[rpos(np.ones(len(gt), int), gt['s1'].to_numpy())].mean() * 100:.2f}%"])
    del ftbl
    by_c = missed.groupby(["country", "src"]).size()
    ex_idx = sorted(rng.sample(range(len(missed)), min(25, len(missed))))
    str_cols = ["entity_id", "name_raw", "addr_raw", "name_core", "name_alt", "addr_core"]
    stbl = pq.read_table(CACHE / "train_records.parquet", columns=str_cols)
    sa = stbl.take(m_s1[ex_idx]).to_pylist()
    sb = stbl.take(m_rec[ex_idx]).to_pylist()
    del stbl
    ex = [[missed["country"].iat[i], a_["entity_id"], a_["name_raw"], a_["addr_raw"], a_["name_core"], a_["addr_core"],
           b_["entity_id"], b_["name_raw"], b_["addr_raw"], b_["name_core"], b_["name_alt"], b_["addr_core"]]
          for i, a_, b_ in zip(ex_idx, sa, sb)]
    lines += [f"## 4. Missed true pairs at the chosen budget (k={k0}, K={K0})", "",
              f"{len(missed):,} missed of {len(gt):,} true pairs ({len(missed) / len(gt) * 100:.2f}%). By country/source: "
              + ", ".join(f"{c}/S{s}: {n:,}" for (c, s), n in by_c.items()), "",
              md_table(["flag", "share of missed pairs", "share among all true pairs"], flag_rows), "",
              "25 random missed pairs (raw, then normalised):", "",
              md_table(["country", "S1 id", "S1 name", "S1 address", "S1 name_core", "S1 addr_core",
                        "record id", "record name", "record address", "record name_core", "record name_alt",
                        "record addr_core"], ex), ""]

    # ------------------------------------------------------------- test
    test_rows = []
    rec1t = pq.read_table(CACHE / "test_records.parquet", columns=["idx", "country"], filters=[("src", "=", 1)]).to_pandas()
    cand_t = pq.read_table(CACHE / "test_candidates.parquet",
                           columns=["s1", "src", "idx", "country", "sim_name", "sim_addr", "score"]).to_pandas()
    for country in country_list("test"):
        st = json.loads(stats_path("test", country).read_text(encoding="utf-8"))
        runtime_rows.append(["test", country, f"{st['timing']['keys'] / 60:.1f}", f"{st['timing']['pairs'] / 60:.1f}",
                             f"{st['timing']['total'] / 60:.1f}", f"{st['peak_rss_gib']:.1f}"])
        c = cand_t[cand_t["country"] == country]
        ids = rec1t.loc[rec1t["country"] == country, "idx"].to_numpy()
        cps = np.bincount(c["s1"].to_numpy(), minlength=int(rec1t["idx"].max()) + 1)[ids]
        n_rec = pq.read_table(CACHE / "test_records.parquet", columns=["src"],
                              filters=[("country", "=", country)]).num_rows - len(ids)
        tr_ = train_cps.get(country)
        test_rows.append([country, f"{len(ids):,}", f"{len(c):,}", *cand_stats(cps),
                          f"{tr_.mean():.1f}" if tr_ is not None else "— (unseen in train)"])
        near = (c["sim_name"] >= NEAR_NAME) & (c["sim_addr"] >= NEAR_ADDR)
        best = c.groupby((c["src"].to_numpy().astype(np.int64) << 32) | c["idx"].to_numpy())["score"].max().to_numpy()
        density[("test", country)] = {"near_per_s1": near.sum() / len(ids), "best_q": np.percentile(best, [5, 25, 50, 75, 95]),
                                      "rec_with_cand": len(best) / n_rec}
    tr_total = sum(len(v) for v in train_cps.values())
    lines += [f"## 5. Test at the chosen budget (k={k0}, K={K0})", "",
              md_table(["country", "test S1", "pairs", "cand/S1 mean", "p50", "p95", "max", "train cand/S1 mean"], test_rows), "",
              f"Total test pairs: {len(cand_t):,} (train at the same budget: "
              f"{next(g['pairs'] for g in budget['grid'] if (g['k'], g['K']) == (k0, K0)):,} for {tr_total:,} S1).", "",
              "## 6. Density diagnostic", "",
              f"Near-duplicate candidates = sim_name >= {NEAR_NAME} and sim_addr >= {NEAR_ADDR} (at the chosen budget). "
              "Best score = each S2/S3 record's maximum candidate score (records with >= 1 candidate).", "",
              md_table(["split", "country", "near-dup cand per S1", "rule precision vs GT", "rule recall vs GT",
                        "records with >= 1 candidate", "best q5", "q25", "q50", "q75", "q95"],
                       [[s, c, f"{d['near_per_s1']:.3f}",
                         f"{d['near_precision'] * 100:.2f}%" if "near_precision" in d else "-",
                         f"{d['near_recall'] * 100:.2f}%" if "near_recall" in d else "-",
                         f"{d['rec_with_cand'] * 100:.2f}%", *[f"{v:.1f}" for v in d["best_q"]]]
                        for (s, c), d in density.items()]), ""]

    # ------------------------------------------------------------- runtime
    norm_rows = []
    for split in ("train", "test"):
        p = CACHE / f"{split}_normalize_stats.json"
        if p.exists():
            ns = json.loads(p.read_text(encoding="utf-8"))
            norm_rows.append([split, "normalize (all countries)", f"{ns['seconds'] / 60:.1f}", f"{ns['peak_rss_gib']:.1f}"])
    lines += ["## 7. Runtime and peak RAM", "",
              md_table(["split", "stage", "minutes", "peak RSS GiB"], norm_rows), "",
              "Blocking per country (minutes; keys, pairs = cumulative checkpoints; total includes scoring). "
              "Peak RSS = peak working set of the whole process, which includes the in-process DuckDB engine (capped at 6 GB):", "",
              md_table(["split", "country", "keys", "pairs", "total", "peak RSS GiB"], runtime_rows), ""]
    (REPORTS / "blocking_report.md").write_text("\n".join(lines), encoding="utf-8")
    log("wrote reports/blocking_report.md")


if __name__ == "__main__":
    main()
