"""Normalisation diagnostics -> reports/normalization_report.md.

Usage (from code/business_entity_resolution/, after normalising train and test):
    python -m src.norm_report

BEFORE = the EDA normalisation (``text_norm.normalize``: lower-case, accents,
punctuation) on the raw fields; AFTER = the new name_core / name_alt / addr_core.
"""

from __future__ import annotations

import json
import random
from collections import Counter

import numpy as np
import pyarrow as pa
import pyarrow.compute as pc
import pyarrow.parquet as pq
from rapidfuzz import fuzz
from rapidfuzz.process import cpdist

from . import text_norm as tn
from .data import ARTIFACTS, CACHE, REPORTS, SEED, gt_pairs, log
from .eda import md_table, p2
from .translit import DICT_PATH, INDIC_RE, STATE_MAP_PATH, normalize_indic_token, romanize

CHUNK = 2_000_000
QS = [1, 5, 10, 25]


def tsr(a, b) -> np.ndarray:
    """Chunked element-wise token_set_ratio of two aligned arrays."""
    out = np.empty(len(a), np.float32)
    for s in range(0, len(a), CHUNK):
        out[s:s + CHUNK] = cpdist(a.slice(s, CHUNK).to_pylist(), b.slice(s, CHUNK).to_pylist(),
                                  scorer=fuzz.token_set_ratio, workers=-1)
    return out


def share_token(a, b) -> np.ndarray:
    """>= 1 shared whitespace token per aligned pair."""
    out = np.zeros(len(a), bool)
    for s in range(0, len(a), CHUNK):
        for j, (x, y) in enumerate(zip(a.slice(s, CHUNK).to_pylist(), b.slice(s, CHUNK).to_pylist())):
            if x and y and not set(x.split()).isdisjoint(y.split()):
                out[s + j] = True
    return out


def q(x: np.ndarray) -> list[str]:
    return [f"{v:.1f}" for v in np.percentile(x, QS)]


def indic_coverage(split: str, token_dict: dict) -> dict:
    """Occurrence-weighted share of Indic name tokens covered by the dictionary."""
    tot = cov = 0
    distinct = Counter()
    tbl = pq.read_table(CACHE / f"{split}_records.parquet", columns=["name_raw"],
                        filters=[("name_has_indic", "=", True)])
    for s in tbl.column("name_raw").to_pylist():
        for m in INDIC_RE.finditer(s):
            w = normalize_indic_token(m.group())
            if not w:
                continue
            distinct[w] += 1
            tot += 1
            cov += w in token_dict
    return {"occurrences": tot, "covered": cov, "coverage": cov / tot if tot else float("nan"),
            "distinct_tokens": len(distinct), "distinct_covered": sum(1 for w in distinct if w in token_dict),
            "top_uncovered": [(w, c) for w, c in distinct.most_common() if w not in token_dict][:15]}


def main() -> None:
    rng = random.Random(SEED)
    lines = ["# Normalization report (v1)", "",
             "Generated by `python -m src.norm_report`. BEFORE = EDA normalisation of raw fields "
             "(`text_norm.normalize`); AFTER = `name_core` (max with `name_alt` for similarity) and `addr_core` "
             "from `src.normalize`.", ""]

    # --- transliteration artifacts
    td = json.loads(DICT_PATH.read_text(encoding="utf-8"))
    sm = json.loads(STATE_MAP_PATH.read_text(encoding="utf-8"))
    st = json.loads((ARTIFACTS / "translit_stats.json").read_text(encoding="utf-8"))
    mp = td["mappings"]
    lines += ["## 1. Indic transliteration", "",
              f"Learned from {st['indic_name_pairs']:,} train true pairs whose noisy name contains Indic text "
              f"({st['distinct_indic_tokens_aligned']:,} distinct Indic tokens aligned). Kept mappings with "
              f"count >= {td['min_count']} and share >= {td['min_share']}: **{len(mp):,} tokens**. "
              f"State component map: **{len(sm['mappings'])} entries** (from {st['indic_addr_pairs']:,} pairs).", ""]
    rows = []
    for split in ("train", "test"):
        c = indic_coverage(split, mp)
        rows.append([split, f"{c['occurrences']:,}", f"{c['coverage'] * 100:.2f}%", f"{c['distinct_tokens']:,}",
                     f"{c['distinct_covered']:,}", ", ".join(f"{w}({n})" for w, n in c["top_uncovered"]) or "-"])
        log(f"coverage {split}: {c['coverage']:.4f}")
    lines += ["Occurrence-weighted dictionary coverage of Indic name tokens (all sources; rule-based "
              "fallback handles the rest):", "",
              md_table(["split", "Indic token occurrences", "covered by dictionary", "distinct tokens",
                        "distinct covered", "most frequent uncovered (count)"], rows), ""]
    sample = rng.sample(sorted(mp), min(30, len(mp)))
    lines += ["30 random dictionary mappings (with the rule-based romanisation for comparison):", "",
              md_table(["Indic token", "learned", "rule-based", "count"],
                       [[w, mp[w], romanize(w), td["counts"][w]] for w in sample]), "",
              "State component map:", "",
              md_table(["native component", "canonical state", "votes"],
                       [[k, v, sm["counts"][k]] for k, v in sm["mappings"].items()]), ""]

    # --- before / after on train true pairs
    log("loading train pairs")
    gt = gt_pairs()
    cols = ["src", "idx", "country", "name_raw", "addr_raw", "name_core", "name_alt", "addr_core"]
    rec = pq.read_table(CACHE / "train_records.parquet", columns=cols)
    src = rec.column("src").to_numpy()
    offs = {s: int(np.flatnonzero(src == s)[0]) for s in (1, 2, 3)}
    a_pos = pa.array(gt["s1"].to_numpy() + offs[1])
    b_pos = pa.array(gt["idx"].to_numpy() + np.where(gt["src"].to_numpy() == 2, offs[2], offs[3]))

    def side(col: str):
        c = rec.column(col).combine_chunks()
        return c.take(a_pos), c.take(b_pos)

    log("BEFORE metrics")
    an, bn = (tn.normalize(x) for x in side("name_raw"))
    aa, ba = (tn.normalize(x) for x in side("addr_raw"))
    before = {"eq": pc.fill_null(pc.and_(pc.equal(an, bn), pc.not_equal(an, "")), False).to_numpy(zero_copy_only=False),
              "name": tsr(an, bn), "addr": tsr(aa, ba), "sn": share_token(an, bn), "sa": share_token(aa, ba)}
    del an, bn, aa, ba
    log("AFTER metrics")
    ac, bc = side("name_core")
    _, balt = side("name_alt")
    ad, bd = side("addr_core")
    name_after = np.maximum(tsr(ac, bc), tsr(ac, balt))
    after = {"eq": pc.fill_null(pc.and_(pc.equal(ac, bc), pc.not_equal(ac, "")), False).to_numpy(zero_copy_only=False),
             "name": name_after, "addr": tsr(ad, bd), "sn": share_token(ac, bc), "sa": share_token(ad, bd)}
    del ac, bc, balt, ad, bd
    ctry, gsrc = gt["country"].to_numpy(), gt["src"].to_numpy()
    rows = []
    for c in sorted(set(ctry)):
        for s in (2, 3, None):
            m = (ctry == c) & ((gsrc == s) if s else True)
            lab = f"S{s}" if s else "S2+S3"
            for tag, d in (("before", before), ("after", after)):
                rows.append([c, lab, tag, f"{m.sum():,}", p2(d["eq"][m].sum(), m.sum()), *q(d["name"][m]),
                             *q(d["addr"][m]), p2(d["sn"][m].sum(), m.sum()), p2(d["sa"][m].sum(), m.sum())])
    lines += ["## 2. Train true pairs: before vs after", "",
              "Name similarity AFTER = max(token_set_ratio(S1 core, record core), token_set_ratio(S1 core, "
              "record alt)). Empty sides score 0. Exact equality needs a non-empty value.", "",
              md_table(["country", "source", "", "pairs", "= name (norm / core)",
                        *[f"name q{x}" for x in QS], *[f"addr q{x}" for x in QS],
                        ">=1 shared name token", ">=1 shared addr token"], rows), ""]

    # --- examples
    lines += ["## 3. Examples (raw -> normalised)", ""]
    ex_cols = ["entity_id", "name_raw", "name_core", "name_alt", "addr_raw", "addr_core", "state"]
    for split, country, n in (("train", "India", 15), ("train", "US", 15), ("test", "France", 15)):
        t = pq.read_table(CACHE / f"{split}_records.parquet", columns=ex_cols + ["src"],
                          filters=[("country", "=", country)])
        pick = sorted(rng.sample(range(t.num_rows), n))
        rows = [[f"S{t.column('src')[i].as_py()}"] + [t.column(c)[i].as_py() or "" for c in ex_cols] for i in pick]
        # prefer showing some Indic / marker cases for India
        lines += [f"### {split} {country}", "", md_table(["src"] + ex_cols, rows), ""]
    if (CACHE / "train_records.parquet").exists():
        t = pq.read_table(CACHE / "train_records.parquet", columns=ex_cols + ["src"],
                          filters=[("name_has_indic", "=", True)])
        pick = sorted(rng.sample(range(t.num_rows), 10))
        lines += ["### train India, Indic-script names (10 extra)", "",
                  md_table(["src"] + ex_cols, [[f"S{t.column('src')[i].as_py()}"] + [t.column(c)[i].as_py() or ""
                                                                                     for c in ex_cols] for i in pick]), ""]
    (REPORTS / "normalization_report.md").write_text("\n".join(lines), encoding="utf-8")
    log("wrote reports/normalization_report.md")


if __name__ == "__main__":
    main()
